language: java
before_install: mvn install -DskipTests=true -DfinalName=xslt-factory-gui-$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Gncj7vxh4ghwQANAAFYDAeWELECXfDJtojXGlV7iFwEYF4UlMMoF9brWMilGElFzdv/MN/GHbnHfM3vlySHymZnZKq87eDG/BH1O1eLpR1ONamAj/PdL/87tgH0yj5fT2jMvx5jeN0i+NuObha1YrmkcH16e4nflEf25esAtG3k=
  file: target/xslt-factory-gui-$TRAVIS_TAG-jar-with-dependencies.jar
  on:
    repo: fusepoolP3/p3-xslt-factory-gui
    tags: true
    all_branches: true
